#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#    Jul 30, 2019 06:28:17 PM -0000  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import jeu_support

from tkinter import *
from tkinter import messagebox
import random

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    jeu_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    jeu_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:

    global rd
    tab=["Mali","sénégal","Liberia","Ghana","Zambie","Burkina-faso","Cote d'Ivoire","Nigéria","Bénin","Guinée"]
    rd=random.sample(tab,2)
    def recupere(self):

        # messagebox.askretrycancel("valeur du texte","val")
        self.Message3.configure(text="{} vs {}".format(rd[0],rd[1]))
        self.Message3.configure(foreground="blue")
        self.Button3.configure(text="Rejouer")
        # self.Button1.configure(command=self.prendre)
    
    def prendre(self):
        cpt=0
        msg=self.Entry1.get()
        ga=random.choice(rd)
        if not msg:
            messagebox.showerror("valeur du texte","vous n'avez rien saisi!")
        elif ga.lower()==msg.lower():
            cpt=cpt+10
            avis=messagebox.showinfo("valeur du texte","bravoo!!!,vous avez trouvé. \n vous marquez donc 10 pints!")
            self.Message2.configure(text= "{} pts".format(cpt))
            # if avis:
            #     self.Entry1.delete(0, END)
            #     self.recupere
                
            # else:
            #         messagebox.showinfo("bye bye","bye bye bye")
        else:
            messagebox.showerror("desolé!","Desolé, vous avez perdu! \n Le gagnant est {}".format(ga))
            cpt=00
            self.Message2.configure(text= "{} pts".format(cpt))


    def rejouer(self):
        self.Entry1.delete(0, END)
        self.Message3.configure(text="{} vs {}".format(rd[0],rd[1]))
        self.Message3.configure(foreground="blue")
        self.Button3.configure(text="jouer")
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font12 = "-family {Segoe UI Black} -size 15 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font13 = "-family {Segoe UI} -size 13 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font14 = "-family {Courier New} -size 12 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font15 = "-family {Segoe UI} -size 11 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font16 = "-family {Segoe UI} -size 11 -weight normal -slant "  \
            "italic -underline 0 -overstrike 0"
        font17 = "-family {Segoe UI Black} -size 14 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font18 = "-family {Segoe UI} -size 12 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font19 = "-family {Segoe UI} -size 12 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font21 = "-family {Segoe UI Black} -size 24 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("872x547+239+99")
        top.title("Jeu de paris")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.654, rely=0.018, relheight=0.96, relwidth=0.304)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#6bd3ff")
        self.Frame1.configure(width=265)

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.075, rely=0.038, height=41, width=224)
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font17)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Vos Scores''')
        self.Label2.configure(width=224)

        self.Message2 = tk.Message(self.Frame1)
        self.Message2.place(relx=0.075, rely=0.19, relheight=0.158
                , relwidth=0.755)
        self.Message2.configure(background="#d9d9d9")
        self.Message2.configure(font=font19)
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''points''')
        self.Message2.configure(width=200)
        

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.189, rely=0.514, height=34, width=127)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d87504")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font=font18)
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Jouer''')
        self.Button3.configure(width=127)
        self.Button3.configure(command=self.rejouer)

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.034, rely=0.018, relheight=0.96, relwidth=0.614)

        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="4")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d8b1ab")
        self.Frame2.configure(width=535)

        self.Label1 = tk.Label(self.Frame2)
        self.Label1.place(relx=0.075, rely=0.038, height=41, width=434)
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font12)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Jeu de Paris Aléatoire''')
        self.Label1.configure(width=434)

        self.Entry1 = tk.Entry(self.Frame2)
        self.Entry1.place(relx=0.112, rely=0.495,height=22, relwidth=0.381)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font=font14)
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Button1 = tk.Button(self.Frame2)
        self.Button1.place(relx=0.598, rely=0.476, height=34, width=137)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#296fd8")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font13)
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Jouer''')
        self.Button1.configure(width=137)
        self.Button1.configure(command=self.prendre)

        self.Button2 = tk.Button(self.Frame2)
        self.Button2.place(relx=0.243, rely=0.4, height=34, width=247)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="orange")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font15)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Cliquez pour commencer''')
        self.Button2.configure(width=247)
        self.Button2.configure(command=self.recupere)

        self.Message1 = tk.Message(self.Frame2)
        self.Message1.place(relx=0.112, rely=0.705, relheight=0.158
                , relwidth=0.729)
        self.Message1.configure(background="white")
        self.Message1.configure(font=font16)
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Indication:
pour jouer cliquer sur le bouton en orange puis le bouton jouer en bleu''')
        self.Message1.configure(width=390)

        self.Message3 = tk.Message(self.Frame2)
        self.Message3.place(relx=0.075, rely=0.152, relheight=0.196
                , relwidth=0.804)
        self.Message3.configure(background="#d9d9d9")
        self.Message3.configure(font=font21)
        self.Message3.configure(foreground="#000000")
        self.Message3.configure(highlightbackground="#d9d9d9")
        self.Message3.configure(highlightcolor="black")
        self.Message3.configure(text='''Tableau''')
        self.Message3.configure(width=430)

if __name__ == '__main__':
    vp_start_gui()





